server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://ubuntu-server:9411
  sleuth:
    sampler:
      probability: 1
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true

logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
